"""Order and fill domain objects for event-driven simulation."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping
from uuid import uuid4

import pandas as pd


class OrderSide(str, Enum):
    """Direction of an order."""

    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    """Execution intent supported by the research simulator."""

    MARKET = "market"
    LIMIT = "limit"
    TARGET_WEIGHT = "target_weight"


class OrderStatus(str, Enum):
    """Lifecycle state of a simulated order."""

    CREATED = "created"
    SUBMITTED = "submitted"
    PARTIALLY_FILLED = "partially_filled"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


@dataclass
class Order:
    """Strategy instruction submitted to the simulated broker."""

    symbol: str
    side: OrderSide
    timestamp: pd.Timestamp
    order_type: OrderType = OrderType.MARKET
    quantity: float | None = None
    target_weight: float | None = None
    limit_price: float | None = None
    status: OrderStatus = OrderStatus.CREATED
    order_id: str = field(default_factory=lambda: str(uuid4()))
    metadata: Mapping[str, object] = field(default_factory=dict)

    @classmethod
    def market(
        cls,
        symbol: str,
        side: OrderSide | str,
        quantity: float,
        timestamp: pd.Timestamp | str,
        metadata: Mapping[str, object] | None = None,
    ) -> "Order":
        """Create a market quantity order."""

        return cls(
            symbol=symbol,
            side=side if isinstance(side, OrderSide) else OrderSide(side),
            quantity=float(quantity),
            timestamp=pd.Timestamp(timestamp),
            metadata={} if metadata is None else metadata,
        )

    @classmethod
    def target_weight(
        cls,
        symbol: str,
        target_weight: float,
        timestamp: pd.Timestamp | str,
        metadata: Mapping[str, object] | None = None,
    ) -> "Order":
        """Create a target-weight order for portfolio-style strategies."""

        side = OrderSide.BUY if target_weight >= 0 else OrderSide.SELL
        return cls(
            symbol=symbol,
            side=side,
            order_type=OrderType.TARGET_WEIGHT,
            target_weight=float(target_weight),
            timestamp=pd.Timestamp(timestamp),
            metadata={} if metadata is None else metadata,
        )


@dataclass(frozen=True)
class Fill:
    """Execution result generated by the simulated broker."""

    order_id: str
    symbol: str
    side: OrderSide
    timestamp: pd.Timestamp
    quantity: float
    price: float
    commission: float = 0.0
    slippage: float = 0.0
    metadata: Mapping[str, object] = field(default_factory=dict)

    @property
    def notional(self) -> float:
        """Signed notional; buy is positive, sell is negative."""

        sign = 1.0 if self.side == OrderSide.BUY else -1.0
        return sign * self.quantity * self.price


@dataclass(frozen=True)
class Transaction:
    """Portfolio ledger entry derived from a fill."""

    fill: Fill
    cash_delta: float
    position_delta: float
    realized_pnl: float = 0.0
